### ISSUE TITLE
Highlight updated fields

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#11]
User Story: As a staff or admin  user, I want the system to highlight the fields that have been updated so that I (and others) know which fields have new data.

Acceptance Criteria:
- [x] 1. The system shall display updated fields in a way that calls them out (style TBD) to notify the user that they have been changed. Any of the following actions shall be considered a change:
* Change value of field
* Remove value (previously filled)
* Add new value (previously blank)

**Comment by kphan1990** [comment]
Verified in Working environment that all acceptance criteria are met.
