### ISSUE TITLE
Show Delta for updated fields

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#12]
User Story: As a SSO user/lead, I want the system to show me the delta between past quarter and current quarter data so that I am aware of the change.

Acceptance Criteria:

- [x]  1. The system shall display the previous value for a field if a user has updated a field and saved the form (if the value has not changed from the previous quarter's value, the system shall ignore the change).
- [x]  2. Scenario: if a user changes the value to a new value, and later changes it back to the previous quarter's value, the system shall ignore the change.

**Comment by kphan1990** [comment]
Moving to Sprint 2.

**Comment by kphan1990** [comment]
Moving  on behalf of Matt

**Comment by kphan1990** [comment]
Verified on 1/5/2017. Functionality working as expected. Checked off acceptance criteria boxes.
