### ISSUE TITLE
Update Status when form is Validated

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#20]
User Story: As a GSA IT officer, I want to flag a form that has been validated by me so that I can push it for final review and validation. 

Related to: #19 

Acceptance Criteria:

- [x]  1. The system shall display an option for the user with "admin" role  to validate or reject a submitted form. 
- [x]  2. The system shall indicate that the form has been validated (/) or rejected (X).

**Comment by kphan1990** [comment]
Moving to Sprint 2.

**Comment by kphan1990** [comment]
Verified in Working environment that the system displays an icon indicator next to each data center name when the admin rejects or validates the form.
