### ISSUE TITLE
Dashboard/Past Report layout

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#22]
User Story: As a user, I want all past reports organized by year, then quarter, then regions so that it is easier for me to find past reports.

Acceptance Criteria:

- [x]  1. The system shall display all current or past data center reports in the following hierarchy:
* Year (YYYY)
* Quarter (Q1, Q2, Q3, Q4)
* Region (Breakdown TBD?)

- [x]  2.  All users shall be able to view all past quarter data.. 
- [x] 3. Only Admin user can export past quarter data to a CSV file.

**Comment by kphan1990** [comment]
Verified in Working environment that all acceptance criteria are met.
