### ISSUE TITLE
Global Search: Data Center ID/Name

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#23]
User Story: As a user, I want to be able to search for data using Data Center ID/Name anywhere I am on the application so that I can quickly find the data center/report I want.

Permission: TBD

Acceptance Criteria:
- [ ]  1. The system shall display a text field search criteria on all of the application pages (refer to as global search criteria going forward).
- [ ]  2. The global search criteria shall search using Data Center ID and Data Center Name.
- [ ]  3. If no results match with the user's input, the system shall display an error: "Invalid Data Center ID or Name."
- [ ]  4. The system shall display all results matching the user's input in the results page (QUESTION- see comment) - showing all past & current reports containing the Data Center ID or Name that the user entered.

**Comment by kphan1990** [comment]
No longer applicable. This item is cancelled. An alternative search solution has been implemented and is working as expected.
