### ISSUE TITLE
Audit: Field level changes

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#24]
User Story: As an admin, I want the system to track changes made by any user at a field level so that I have an audit trail for each data center report/form.

Related to: story #12 

Acceptance Criteria:

- [ ]  1. The system shall capture the following information whenever a user updates and saves a field:
* Who made the change - "Modified By"
* Date & Time when the change was made - "Modified Date"
* The value prior to the change - "Previous Value"

- [ ] 2. The system shall track the change for each field every time it is updated and saved. Scenario: 
* User changes Rack Count from 10 to 15 on 11/1/2016.
* User changes Rack Count from 15 back to 10 on 11/2/2016.
* User changes Rack Count from 10 to 9 on 11/3/2016.
* Expected Audit Trail for field "Rack Count" = three separate entries.

**Comment by kphan1990** [comment]
Moving to Sprint 2.
