### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by kphan1990** [Ventera-Corporation/gsa-dcoi#62]
User Story: As a user, I want to be able to build my own query using 4 different fields so that I can create and filter data.

Acceptance Criteria:
- [x] 1. On Advanced Search criteria page, display the following fields:
- Data Center ID
- Data Center Name
- Quarter/year
- Closing Stage

**Comment by sneelz** [comment]
Added front-end for query fields

**Comment by kphan1990** [comment]
Cancelled. This item is no longer applicable since another search/query solution has been implemented.
