### ISSUE TITLE
Data Center FORM

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#7]
User Story: As a SSO user, I want to be able to enter my component's inventory and other data for the most recent quarter in a form so that I don't have to fill out an excel spreadsheet.

**Acceptance Criteria:**
- [x] 1.  A user with "user" and "Facility" and/or "Server" role shall also be able to edit the data in the form layout.
- [x] 2. The Facility user  shall be able to edit only the Facility section on the data center form.
- [x] 3. The Server user shall be able to edit only the Server section on the Field Office tab to which he/she is assigned. They cannot edit the Server section for other Field Offices within the same Data Center unless they are assigned to them.
- [x] 4. The Facility + Server user shall have permission to take similar actions as #2 and #3.
- [x] 5. The system shall display a Submit button on every Data Center form.

**Comment by kphan1990** [comment]
Verified in Working environment that all acceptance criteria are met.
