### ISSUE TITLE
Pre-populate data on new quarter form

### ISSUE THREAD

**Issue by ncrismali** [Ventera-Corporation/gsa-dcoi#8]
User Story: As a SSO user, I want to [some data fields?] to be prepopulated based on last quarter information for my component so that I can save time and only update what I need updating

Acceptance Criteria:
- [x] 1. The system shall pre-populate all the fields that contained data from the previous quarter.
- [x] 2. If a field previously did not have a value (blank), the system shall display "None".

**Comment by kphan1990** [comment]
Verified in Working environment that all acceptance criteria are met.
